config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  authenticated :user do
    root "home#user", as: :authenticated_root
  end

  root "home#index"
  get "user", to: "home#user"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  resources :tasks
  resources :contacts
  # Rutas API (JSON)
  namespace :api, defaults: { format: :json } do
    resources :contacts
    get "test", to: "test#index"
    get "user", to: "users#show"

    match "*unmatched", to: "errors#route_not_found", via: :all
  end
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true

  after_create_commit { broadcast_prepend_to "tasks" }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all.order(:created_at)
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to :tasks, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to :tasks, notice: "Task was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.update!(completed: !@task.completed?)

    respond_to do |format|
      format.html { redirect_to tasks_path, notice: "Task was successfully updated.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.expect(task: [ :name, :completed ])
    end
end

app/views/tasks/_form.html.erb
<%= turbo_frame_tag "task_#{task.id}", class: "w-full" do %>
  <%= form_with(model: task, class: "contents", data: { turbo_frame: "_top" }) do |form| %>

    <div class="my-5">
      <%= form.label :name %>
      <%= form.text_field :name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": task.errors[:name].none?, "border-red-400 focus:outline-red-600": task.errors[:name].any?}] %>
    </div>

    <div class="my-5">
      <%= form.label :completed %>
      <%= form.check_box :completed, class: "block shadow-sm rounded-md border px-3 py-2 mt-2" %>
    </div>
    <div class="inline">
      <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
    </div>
  <% end %>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>" class="w-full sm:w-auto my-5 space-y-5 flex flex-row justify-between items-center pb-5 sm:pb-0">
  <%= button_to task, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 font-medium cursor-pointer text-gray-500", data: { turbo_confirm: "Are you sure?" } do %>
    <%= task.completed? ? content_tag(:span, "check_circle", class: "material-icons") : content_tag(:span, "circle", class: "material-icons") %>
  <% end %>
  <%= turbo_frame_tag "task_#{task.id}", class: "w-full my-5 space-y-5 flex flex-row justify-between items-center pb-5 sm:pb-0" do %>
    <p class="ml-2">
      <%= task.name %>
    </p>
    <%= link_to edit_task_path(task), class: "w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium w-auto flex flex-col sm:flex-row space-x-2 space-y-2" do %>
      <span class="material-icons">edit</span>
    <% end %>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<% content_for :title, "Editing task" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing task</h1>

  <%= render "form", task: @task %>

  <%= link_to "Show this task", @task, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to tasks", tasks_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/tasks/index.html.erb
<% content_for :title, "Tasks" %>
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">To Do</h1>
    <%= link_to "New task", new_task_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>
  <%= turbo_stream_from "tasks" %>
  <%= turbo_frame_tag "tasks", class: "divide-y divide-gray-200 table min-w-full" do %>
    <%= render @tasks %>
  <% end %>
</div>

app/views/tasks/new.html.erb
<% content_for :title, "New task" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New task</h1>

  <%= render "form", task: @task %>

  <%= link_to "Back to tasks", tasks_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/tasks/show.html.erb
<% content_for :title, "Showing task" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing task</h1>

  <%= render @task %>

  <%= link_to "Edit this task", edit_task_path(@task), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to tasks", tasks_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this task", @task, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>