config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  authenticated :user do
    root "home#user", as: :authenticated_root
  end

  root "home#index"
  get "user", to: "home#user"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  resources :tasks
  resources :contacts
  # Rutas API (JSON)
  namespace :api, defaults: { format: :json } do
    resources :contacts
    get "test", to: "test#index"
    get "user", to: "users#show"

    match "*unmatched", to: "errors#route_not_found", via: :all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [ :user ]

  def index
    @demos = Demo.all
  end

  def user
  end
end

app/views/home/index.html.erb
<div>
  <h1 class="text-4xl font-bold text-center mb-8">
    Portfolio Lexdrel
  </h1>

  <% if user_signed_in? %>
    <p class="mb-4">Welcome back, <%= current_user.email %>!</p>
    <%= link_to "Go to Dashboard", user_path, class: "bg-indigo-600 text-white px-4 py-2 rounded" %>
    <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "bg-red-500 text-white px-4 py-2 rounded mt-2" %>
  <% else %>
    <div class="flex justify-center space-x-4 mb-8">
      <%= link_to "Sign In", new_user_session_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
      <%= link_to "Sign Up", new_user_registration_path, class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded" %>
      <%= button_to "Sign in with LinkedIn", user_linkedin_omniauth_authorize_path, data: { turbo: false }, class: "bg-[#0077b5] hover:bg-[#005582] text-white font-bold py-2 px-4 rounded" %>
    </div>
  <% end %>

  <p>List of demo strings</p>


  <ul class="list-disc list-inside text-lg">
    <% @demos.each do |demo| %>
      <li class="ml-4">
        <%= demo.title %>
      </li>
    <% end %>
  </ul>
</div>

app/views/home/user.html.erb
<h1>You're an authenticated user</h1>
<%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "bg-red-500 text-white px-4 py-2 rounded mt-4" %>