config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  authenticated :user do
    root "home#user", as: :authenticated_root
  end

  root "home#index"
  get "user", to: "home#user"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  resources :tasks
  resources :contacts
  # Rutas API (JSON)
  namespace :api, defaults: { format: :json } do
    resources :contacts
    get "test", to: "test#index"
    get "user", to: "users#show"

    match "*unmatched", to: "errors#route_not_found", via: :all
  end
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/api/contacts_controller.rb
module Api
  class ContactsController < ApplicationApiController
      before_action :set_contact, only: %i[ show edit update destroy ]

      # GET /api/contacts
      def index
        @contacts = Contact.all
      end

      # GET /contacts/1 or /contacts/1.json
      def show
      end

      # GET /contacts/new
      def new
        @contact = Contact.new
      end

      # GET /contacts/1/edit
      def edit
      end

      # POST /contacts or /contacts.json
      def create
        @contact = Contact.new(contact_params)

        respond_to do |format|
          if @contact.save
            format.json { render :show, status: :created, location: @contact }
            ContactMailer.new_contact_form(@contact.email, @contact.name).deliver_now
          else
            format.json { render json: @contact.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /contacts/1 or /contacts/1.json
      def update
        respond_to do |format|
          if @contact.update(contact_params)
            format.json { render :show, status: :ok, location: @contact }
          else
            format.json { render json: @contact.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /contacts/1 or /contacts/1.json
      def destroy
        @contact.destroy!

        respond_to do |format|
          format.json { head :no_content }
        end
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_contact
          @contact = Contact.find(params.expect(:id))
        end

        # Only allow a list of trusted parameters through.
        def contact_params
          params.expect(contact: [ :name, :email, :reason, :phone, :message ])
        end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: "Contact was successfully created." }
        ContactMailer.new_contact_form(@contact.email, @contact.name).deliver_now
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: "Contact was successfully updated.", status: :see_other }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy!

    respond_to do |format|
      format.html { redirect_to contacts_path, notice: "Contact was successfully destroyed.", status: :see_other }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.expect(contact: [ :name, :email, :reason, :phone, :message ])
    end
end

app/views/contacts/_contact.html.erb
<div id="<%= dom_id contact %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Name:</strong>
    <%= contact.name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Email:</strong>
    <%= contact.email %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Reason:</strong>
    <%= contact.reason %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Phone:</strong>
    <%= contact.phone %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Message:</strong>
    <%= contact.message %>
  </div>
</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, class: "contents") do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul class="list-disc ml-6">
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": contact.errors[:name].none?, "border-red-400 focus:outline-red-600": contact.errors[:name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": contact.errors[:email].none?, "border-red-400 focus:outline-red-600": contact.errors[:email].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :reason %>
    <%= form.number_field :reason, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": contact.errors[:reason].none?, "border-red-400 focus:outline-red-600": contact.errors[:reason].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :phone %>
    <%= form.text_field :phone, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": contact.errors[:phone].none?, "border-red-400 focus:outline-red-600": contact.errors[:phone].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :message %>
    <%= form.textarea :message, rows: 4, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": contact.errors[:message].none?, "border-red-400 focus:outline-red-600": contact.errors[:message].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<% content_for :title, "Editing contact" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing contact</h1>

  <%= render "form", contact: @contact %>

  <%= link_to "Show this contact", @contact, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to contacts", contacts_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/contacts/index.html.erb
<% content_for :title, "Contacts" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Contacts</h1>
    <%= link_to "New contact", new_contact_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="contacts" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @contacts.any? %>
      <% @contacts.each do |contact| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render contact %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", contact, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_contact_path(contact), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", contact, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No contacts found.</p>
    <% end %>
  </div>
</div>

app/views/contacts/new.html.erb
<% content_for :title, "New contact" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New contact</h1>

  <%= render "form", contact: @contact %>

  <%= link_to "Back to contacts", contacts_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/contacts/show.html.erb
<% content_for :title, "Showing contact" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing contact</h1>

  <%= render @contact %>

  <%= link_to "Edit this contact", edit_contact_path(@contact), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to contacts", contacts_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this contact", @contact, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>